(window.webpackJsonp=window.webpackJsonp||[]).push([[5],{"Kh/G":function(n,t,e){"use strict";e.d(t,"a",(function(){return o}));var r=e("7jDb"),o={inv:{items:[]},workshop:{entities:[]}};r.a.provide_CCC("player.inventoryPush",(function(n,t){n.which.itemStack.count>0&&t.data.entity[n.which.itemStack.name]&&t.addNewObject(n.to.entities,"player.entity",{name:n.which.itemStack.name})&&(n.which.itemStack.count--,t.view.signaler.signal("addedEntity"))}),{which:"itemStack",to:"entities"})},uH5N:function(n,t,e){"use strict";var r=e("7jDb");function o(n,t){var e;if("undefined"==typeof Symbol||null==n[Symbol.iterator]){if(Array.isArray(n)||(e=function(n,t){if(!n)return;if("string"==typeof n)return a(n,t);var e=Object.prototype.toString.call(n).slice(8,-1);"Object"===e&&n.constructor&&(e=n.constructor.name);if("Map"===e||"Set"===e)return Array.from(n);if("Arguments"===e||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(e))return a(n,t)}(n))||t&&n&&"number"==typeof n.length){e&&(n=e);var r=0;return function(){return r>=n.length?{done:!0}:{done:!1,value:n[r++]}}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}return(e=n[Symbol.iterator]()).next.bind(e)}function a(n,t){(null==t||t>n.length)&&(t=n.length);for(var e=0,r=new Array(t);e<t;e++)r[e]=n[e];return r}
//! I don't think these will work under all circumstances,
function i(n,t,e){if(e){for(var r,a=-1,i=4,u=o(n.entries());!(r=u()).done;){var c=r.value,l=c[0],m=c[1];i>3&&!m&&(i=3,a=l),i>2&&m&&0==m.count&&(i=2,a=l),i>1&&m&&m.name==t&&m.count<e&&(i=1,a=l)}return 2==i&&(n[a].name=t,n[a].icon=null),a}var s=n.slice().reverse().findIndex((function(n){return n&&n.name==t&&n.count>0}));return-1==s?-1:n.length-1-s}function u(n,t,e,r){if(t.name){e.count=0;for(var a,i=o(n);!(a=i()).done;){var u=a.value;u&&u.name==t.name&&(e.count+=u.count)}e._result=e.count}else if(t.names)for(var c,l=o(n);!(c=l()).done;){var m=c.value;m&&t.names.indexOf(m.name)>-1&&(e[m.name]?e[m.name]+=m.count:e[m.name]=m.count)}}r.a.addOperation("inventory.add",(function(n,t,e,r){
//! needs to handle a multiplier from args
var a=t.itemStacks;Array.isArray(a)||(a=[a]);for(var u,c=0,l=o(a);!(u=l()).done;){var m=u.value;if(!m.count&&m.amount&&(m.count=m.amount),0!=m.count){var s=m.count*(t.multi||1);c=r.data.item[m.name].stack_size;for(var f=i(n.items,m.name,c);f>-1&&s>0;){var v=Math.min(c-n.items[f].count,s);s-=v,n.items[f].count+=v,f=i(n.items,m.name,c)}s>0&&(
//! Theoretically, this would be the case of all existing inventory
//!   is different than the item or full
!n.maxStacks||n.items.length<n.maxStacks?n.items.push({name:m.name,count:s}):r.graphics.error("Inventory Full"))}}e.part=[]})),r.a.addOperation("inventory.consume",(function(n,t,e,r){var a=t.itemStacks;Array.isArray(a)||(a=[a]);for(var u,c=[],l=o(a);!(u=l()).done;){var m=u.value;!m.count&&m.amount&&(m.count=m.amount);for(var s=i(n.items,m.name),f=m.count*(t.multi||1);s>-1&&f;){var v=Math.min(n.items[s].count,f);n.items[s].count-=v,f-=v,s=i(n.items,m.name)}if(c.push({name:m.name,count:m.count*(t.multi||1)-f}),f&&!t.partial)
//! we have failed to consume all
return r.processTEMP(n,"inventory.add",{itemStacks:c}),e._result=!1,e}e._result=t.partial&&c||!0})),r.a.addOperation("inventory.total",u),r.a.addUtility_CCC("inventory.total",u)},wb4v:function(n,t,e){"use strict";e.d(t,"a",(function(){return u}));e("+Aae");var r=e("EfK0"),o=e("0d46");function a(n,t){var e;if("undefined"==typeof Symbol||null==n[Symbol.iterator]){if(Array.isArray(n)||(e=function(n,t){if(!n)return;if("string"==typeof n)return i(n,t);var e=Object.prototype.toString.call(n).slice(8,-1);"Object"===e&&n.constructor&&(e=n.constructor.name);if("Map"===e||"Set"===e)return Array.from(n);if("Arguments"===e||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(e))return i(n,t)}(n))||t&&n&&"number"==typeof n.length){e&&(n=e);var r=0;return function(){return r>=n.length?{done:!0}:{done:!1,value:n[r++]}}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}return(e=n[Symbol.iterator]()).next.bind(e)}function i(n,t){(null==t||t>n.length)&&(t=n.length);for(var e=0,r=new Array(t);e<t;e++)r[e]=n[e];return r}function u(n){var t=n.from,e=n.to,o=n.options;if((null==o?void 0:o.debug)&&(console.log("debug:"),console.log(t),console.log(e),console.log(o)),0!=(null==o?void 0:o.maxXfer)){var i="entity"==(null==o?void 0:o.toAs)?"recieveItem":"addStack",u=0,c=function(n){(null==o?void 0:o.debug)&&console.log(n);var a=e[i](n);return(null==o?void 0:o.debug)&&console.log(a),a&&t.consumeAll(new r.b(n.name,a)),null==o||o.debug,a},l=(null==o?void 0:o.maxXfer)?function(n){return Math.min(n,o.maxXfer-u)}:function(n){return n};if(null==o?void 0:o.stacks)for(var m,s=a(o.stacks);!(m=s()).done;){c(m.value)}else for(var f,v=a(t.items);!(f=v()).done;){var d=f.value;if(d&&d.name&&0!=d.count&&((!(null==o?void 0:o.types)||o.types.includes(d.name))&&(u+=c({name:d.name,count:l(d.count)}),(null==o?void 0:o.debug)&&console.log("accum: "+u),(null==o?void 0:o.maxXfer)&&o.maxXfer==u)))return}}}o.b.provide("invXfer",u),o.b.provide("invUse",(function(n){switch(n.how){case"sub-n-crement":0===n.from.consume(n.what,n.count)&&(n.to_prop?n.to[n.to_prop]+=n.count:n.to+=n.count)}}))}}]);
//# sourceMappingURL=app~84713d80.cd3c952e059e5ed8add2.bundle.map