(window.webpackJsonp=window.webpackJsonp||[]).push([[5],{"Kh/G":function(t,n,e){"use strict";e.d(n,"a",(function(){return o}));var r=e("7jDb"),o={inv:{items:[]},workshop:{entities:[]}};r.a.provide_CCC("player.inventoryPush",(function(t,n){t.which.itemStack.count>0&&n.data.entity[t.which.itemStack.name]&&n.addNewObject(t.to.entities,"player.entity",{name:t.which.itemStack.name})&&(t.which.itemStack.count--,n.view.signaler.signal("addedEntity"))}),{which:"itemStack",to:"entities"})},uH5N:function(t,n,e){"use strict";var r=e("7jDb");function o(t,n){var e;if("undefined"==typeof Symbol||null==t[Symbol.iterator]){if(Array.isArray(t)||(e=function(t,n){if(!t)return;if("string"==typeof t)return a(t,n);var e=Object.prototype.toString.call(t).slice(8,-1);"Object"===e&&t.constructor&&(e=t.constructor.name);if("Map"===e||"Set"===e)return Array.from(t);if("Arguments"===e||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(e))return a(t,n)}(t))||n&&t&&"number"==typeof t.length){e&&(t=e);var r=0;return function(){return r>=t.length?{done:!0}:{done:!1,value:t[r++]}}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}return(e=t[Symbol.iterator]()).next.bind(e)}function a(t,n){(null==n||n>t.length)&&(n=t.length);for(var e=0,r=new Array(n);e<n;e++)r[e]=t[e];return r}
//! I don't think these will work under all circumstances,
function i(t,n,e){if(e){for(var r,a=-1,i=4,u=o(t.entries());!(r=u()).done;){var c=r.value,l=c[0],m=c[1];i>3&&!m&&(i=3,a=l),i>2&&m&&0==m.count&&(i=2,a=l),i>1&&m&&m.name==n&&m.count<e&&(i=1,a=l)}return 2==i&&(t[a].name=n,t[a].icon=null),a}var s=t.slice().reverse().findIndex((function(t){return t&&t.name==n&&t.count>0}));return-1==s?-1:t.length-1-s}function u(t,n,e,r){if("string"==typeof t&&t.includes("id")&&(t=r.getId(t).items),n.name){e.count=0;for(var a,i=o(t);!(a=i()).done;){var u=a.value;u&&u.name==n.name&&(e.count+=u.count)}e._result=e.count}else if(n.names)for(var c,l=o(t);!(c=l()).done;){var m=c.value;m&&n.names.indexOf(m.name)>-1&&(e[m.name]?e[m.name]+=m.count:e[m.name]=m.count)}}r.a.addOperation("inventory.add",(function(t,n,e,r){
//! needs to handle a multiplier from args
var a=n.itemStacks;Array.isArray(a)||(a=[a]);for(var u,c=0,l=o(a);!(u=l()).done;){var m=u.value;if(!m.count&&m.amount&&(m.count=m.amount),0!=m.count){var s=m.count*(n.multi||1);c=r.data.item[m.name].stack_size;for(var d=i(t.items,m.name,c);d>-1&&s>0;){var f=Math.min(c-t.items[d].count,s);s-=f,t.items[d].count+=f,d=i(t.items,m.name,c)}s>0&&(
//! Theoretically, this would be the case of all existing inventory
//!   is different than the item or full
!t.maxStacks||t.items.length<t.maxStacks?t.items.push({name:m.name,count:s}):r.graphics.error("Inventory Full"))}}e.part=[]})),r.a.addOperation("inventory.consume",(function(t,n,e,r){var a=n.itemStacks;Array.isArray(a)||(a=[a]);for(var u,c=[],l=o(a);!(u=l()).done;){var m=u.value;!m.count&&m.amount&&(m.count=m.amount);for(var s=i(t.items,m.name),d=m.count*(n.multi||1);s>-1&&d;){var f=Math.min(t.items[s].count,d);t.items[s].count-=f,d-=f,s=i(t.items,m.name)}if(c.push({name:m.name,count:m.count*(n.multi||1)-d}),d&&!n.partial)
//! we have failed to consume all
return r.processTEMP(t,"inventory.add",{itemStacks:c}),e._result=!1,e}e._result=n.partial&&c||!0})),r.a.addOperation("inventory.total",u),r.a.addUtility_CCC("inventory.total",u)},wb4v:function(t,n,e){"use strict";e.d(n,"a",(function(){return u}));e("+Aae");var r=e("EfK0"),o=e("0d46");function a(t,n){var e;if("undefined"==typeof Symbol||null==t[Symbol.iterator]){if(Array.isArray(t)||(e=function(t,n){if(!t)return;if("string"==typeof t)return i(t,n);var e=Object.prototype.toString.call(t).slice(8,-1);"Object"===e&&t.constructor&&(e=t.constructor.name);if("Map"===e||"Set"===e)return Array.from(t);if("Arguments"===e||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(e))return i(t,n)}(t))||n&&t&&"number"==typeof t.length){e&&(t=e);var r=0;return function(){return r>=t.length?{done:!0}:{done:!1,value:t[r++]}}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}return(e=t[Symbol.iterator]()).next.bind(e)}function i(t,n){(null==n||n>t.length)&&(n=t.length);for(var e=0,r=new Array(n);e<n;e++)r[e]=t[e];return r}function u(t){var n=t.from,e=t.to,o=t.options;if((null==o?void 0:o.debug)&&(console.log("debug:"),console.log(n),console.log(e),console.log(o)),0!=(null==o?void 0:o.maxXfer)){var i="entity"==(null==o?void 0:o.toAs)?"recieveItem":"addStack",u=0,c=function(t){(null==o?void 0:o.debug)&&console.log(t);var a=e[i](t);return(null==o?void 0:o.debug)&&console.log(a),a&&n.consumeAll(new r.b(t.name,a)),null==o||o.debug,a},l=(null==o?void 0:o.maxXfer)?function(t){return Math.min(t,o.maxXfer-u)}:function(t){return t};if(null==o?void 0:o.stacks)for(var m,s=a(o.stacks);!(m=s()).done;){c(m.value)}else for(var d,f=a(n.items);!(d=f()).done;){var v=d.value;if(v&&v.name&&0!=v.count&&((!(null==o?void 0:o.types)||o.types.includes(v.name))&&(u+=c({name:v.name,count:l(v.count)}),(null==o?void 0:o.debug)&&console.log("accum: "+u),(null==o?void 0:o.maxXfer)&&o.maxXfer==u)))return}}}o.b.provide("invXfer",u),o.b.provide("invUse",(function(t){switch(t.how){case"sub-n-crement":0===t.from.consume(t.what,t.count)&&(t.to_prop?t.to[t.to_prop]+=t.count:t.to+=t.count)}}))}}]);
//# sourceMappingURL=app~84713d80.ef6fe5811316b8fa117a.bundle.map