version: "3.7"

services:
  the-factory-must-grow:
    image: the-factory-must-grow:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
